export const TEACHERS_LIST = [
	{
		id: 1,
		name: 'Professor Dumbledore',
		designation: 'Headmaster',
		subject: 'All',
		attendance: 'Absent',
		priority: 1,
	},
	{
		id: 2,
		name: 'Minerva McGonagall',
		designation: 'Headmistress',
		subject: 'All',
		attendance: 'Absent',
		priority: 2,
	},
	{
		id: 3,
		name: 'Rubeus Hagrid',
		designation: 'Standby Professor',
		subject: 'Potions Master',
		attendance: 'Present',
		priority: 3,
	},
	{
		id: 4,
		name: 'Horace Slughorn',
		designation: 'Professor',
		subject: 'Potions Master',
		attendance: 'Present',
		priority: 4,
	},
	{
		id: 5,
		name: 'Severus Snape',
		designation: 'Professor',
		subject: 'Potions Master',
		attendance: 'Present',
		priority: 5,
	},
	{
		id: 6,
		name: 'Alastor Moody',
		designation: 'Standby Professor',
		subject: 'Defense Against the Dark Arts',
		attendance: 'Absent',
		priority: 3,
	},
	{
		id: 7,
		name: 'Remus Lupin',
		designation: 'Professor',
		subject: 'Defense Against the Dark Arts',
		attendance: 'Present',
		priority: 4,
	},
	{
		id: 8,
		name: 'Gilderoy Lockhart',
		designation: 'Professor',
		subject: 'Defense Against the Dark Arts',
		attendance: 'Present',
		priority: 5,
	},
];
