export const LIST_TEACHER_ATTENDANCE_SUCCESS = 'LIST_TEACHER_ATTENDANCE_SUCCESS';
export const UPDATE_TEACHER_ATTENDANCE_SUCCESS = 'UPDATE_TEACHER_ATTENDANCE_SUCCESS';

// These two will be used in case of async API calls.
// export const LIST_TEACHER_ATTENDANCE_ERROR = 'LIST_TEACHER_ATTENDANCE_ERROR';
// export const LIST_TEACHER_ATTENDANCE_IN_PROGRESS = 'LIST_TEACHER_ATTENDANCE_IN_PROGRESS';
