export const LIST_CURRENT_SCHEDULE_SUCCESS = 'LIST_CURRENT_SCHEDULE_SUCCESS';

// export const LIST_CURRENT_SCHEDULE_ERROR = 'LIST_CURRENT_SCHEDULE_ERROR';
// export const LIST_CURRENT_SCHEDULE_IN_PROGRESS = 'LIST_CURRENT_SCHEDULE_IN_PROGRESS';
